### ISSUE TITLE
Does KDCycleBannerView support Swift?

### ISSUE THREAD

**Issue by jerry-sl** [kingiol/KDCycleBannerView#6]
Does KDCycleBannerView support Swift?  Any Swift Demo?

**Comment by kingiol** [comment]
https://github.com/kingiol/KDCycleBannerView-Swift

**Comment by jerry-sl** [comment]
Why use Swift rewrite the project , now you must maintain two code base.

**Comment by kingiol** [comment]
yes, there are two code base, now i fix some issues, In future, I will only maintain the swift version
